apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
 platform:
   channels:
     - name: stable-4.10
 operators:
   - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
     packages:
       - name: advanced-cluster-management
