apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: mirror-ocp.ocpd.nutarh.lab:8443/openshift
    skipTLS: false
mirror:
 platform:
   channels:
     - name: stable-4.10
       type: ocp
 operators:
   - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
     packages:
       - name: 3scale-operator
       - name: advanced-cluster-management
       - name: amq-broker-rhel8
       - name: amq-online
       - name: amq-streams
       - name: amq7-interconnect-operator
       - name: ansible-automation-platform-operator
       - name: ansible-cloud-addons-operator
       - name: apicast-operator
       - name: aws-efs-csi-driver-operator
       - name: businessautomation-operator
       - name: cincinnati-operator
       - name: cluster-kube-descheduler-operator
       - name: cluster-logging
       - name: clusterresourceoverride
       - name: codeready-workspaces
       - name: codeready-workspaces2
       - name: compliance-operator
       - name: container-security-operator
       - name: costmanagement-metrics-operator
       - name: cryostat-operator
       - name: datagrid
       - name: devworkspace-operator
       - name: dpu-network-operator
       - name: eap
       - name: elasticsearch-operator
       - name: external-dns-operator
       - name: file-integrity-operator
       - name: fuse-apicurito
       - name: fuse-console
       - name: fuse-online
       - name: gatekeeper-operator-product
       - name: idp-mgmt-operator-product
       - name: integration-operator
       - name: jaeger-product
       - name: jws-operator
       - name: kiali-ossm
       - name: klusterlet-product
       - name: kubernetes-nmstate-operator
       - name: kubevirt-hyperconverged
       - name: local-storage-operator
       - name: loki-operator
       - name: mcg-operator
       - name: metallb-operator
       - name: mtc-operator
       - name: mtv-operator
       - name: multicluster-engine
       - name: nfd
       - name: node-healthcheck-operator
       - name: node-maintenance-operator
       - name: numaresources-operator
       - name: ocs-operator
       - name: odf-csi-addons-operator
       - name: odf-lvm-operator
       - name: odf-multicluster-orchestrator
       - name: odf-operator
       - name: odr-cluster-operator
       - name: odr-hub-operator
       - name: openshift-cert-manager-operator
       - name: openshift-gitops-operator
       - name: openshift-pipelines-operator-rh
       - name: openshift-secondary-scheduler-operator
       - name: openshift-special-resource-operator
       - name: opentelemetry-product
       - name: performance-addon-operator
       - name: poison-pill-manager
       - name: ptp-operator
       - name: quay-bridge-operator
       - name: quay-operator
       - name: red-hat-camel-k
       - name: redhat-oadp-operator
       - name: rh-service-binding-operator
       - name: rhacs-operator
       - name: rhpam-kogito-operator
       - name: rhsso-operator
       - name: sandboxed-containers-operator
       - name: serverless-operator
       - name: service-registry-operator
       - name: servicemeshoperator
       - name: skupper-operator
       - name: sriov-network-operator
       - name: submariner
       - name: tang-operator
       - name: vertical-pod-autoscaler
       - name: web-terminal
       - name: windows-machine-config-operator
   - catalog: registry.redhat.io/redhat/certified-operator-index:v4.10
     packages:
       - name: aikit-operator
       - name: ako-operator
       - name: anchore-engine
       - name: anzo-operator
       - name: anzograph-operator
       - name: anzounstructured-operator
       - name: apimatic-codegen-operator
       - name: aqua-operator-certified
       - name: cass-operator
       - name: ccm-node-agent-dcap-operator
       - name: ccm-node-agent-operator
       - name: cilium
       - name: cilium-enterprise
       - name: cisco-hxcsi-operator
       - name: citrix-adc-istio-ingress-gateway-operator
       - name: citrix-cpx-istio-sidecar-injector-operator
       - name: citrix-cpx-with-ingress-controller-operator
       - name: citrix-ingress-controller-operator
       - name: cloud-native-postgresql
       - name: cloudbees-ci
       - name: confluent-for-kubernetes
       - name: couchbase-enterprise-certified
       - name: crunchy-postgres-operator
       - name: datadog-operator-certified
       - name: dell-csi-operator-certified
       - name: dynatrace-operator
       - name: elasticsearch-eck-operator-certified
       - name: entando-k8s-operator
       - name: federatorai-certified
       - name: fep-ansible-operator
       - name: fujitsu-enterprise-operator
       - name: gitlab-runner-operator
       - name: gpu-operator-certified
       - name: grafana-cloud-log-forwarder-operator
       - name: hazelcast-platform-operator
       - name: hpe-csi-operator
       - name: hpe-ezmeral-csi-operator
       - name: ibm-application-gateway-operator
       - name: ibm-block-csi-operator
       - name: ibm-security-verify-operator
       - name: ibmz-mongodb-enterprise-operator
       - name: infinibox-operator-certified
       - name: infoscale-operator
       - name: installkit-customer
       - name: instana-agent-operator
       - name: intel-device-plugins-operator
       - name: iomesh-operator
       - name: joget-dx-operator
       - name: k8s-triliovault
       - name: k8s-triliovault-ibm
       - name: kubemq-operator-marketplace
       - name: kubeturbo-certified
       - name: linstor-operator
       - name: marketplace-games-operator
       - name: memcached-operator-ogaye
       - name: memory-machine-operator
       - name: minio-operator
       - name: mongodb-atlas-kubernetes
       - name: mongodb-enterprise
       - name: neuvector-certified-operator
       - name: nginx-ingress-operator
       - name: nutanixcsioperator
       - name: nvidia-network-operator
       - name: nxiq-operator-certified
       - name: nxrm-operator-certified
       - name: open-liberty-certified
       - name: openshiftartifactoryha-operator
       - name: openshiftxray-operator
       - name: operator-certification-operator
       - name: ovms-operator
       - name: pachyderm-operator
       - name: pcc-operator
       - name: pmem-csi-operator-os
       - name: portworx-certified
       - name: prometurbo-certified
       - name: redhat-marketplace-operator
       - name: redis-enterprise-operator-cert
       - name: rookout-k8s-operator
       - name: runtime-component-operator-certified
       - name: sanstoragecsi-operator-bundle
       - name: seldon-operator-certified
       - name: silicom-sts-operator
       - name: smilecdr-operator
       - name: sriov-fec
       - name: sysdig-certified
       - name: t8c-certified
       - name: tenant-operator
       - name: tigera-operator
       - name: timemachine-operator
       - name: uma-operator
       - name: vfunction-server-operator
       - name: xcrypt-operator
       - name: zabbix-operator-certified